/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kkbjepakrprkvttykcyb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrYmplcGFrcnBya3Z0dHlrY3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MzQ4ODUsImV4cCI6MjA3OTUxMDg4NX0.2HCj-qJu-rwkp0qqf4xcIEDR7uLegSZP-Bl5rSs5kRk"